# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='title', max_length=200, null=True)),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='picture/')),
                ('description', models.TextField()),
                ('project_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profilepic',
            new_name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='awardsapp.Project'),
        ),
    ]
