# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0003_review_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(max_length=250),
        ),
    ]
