# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0005_auto_20181010_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='useability_rating',
            new_name='usability_rating',
        ),
    ]
