# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0007_auto_20181010_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
    ]
