# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0009_auto_20181011_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='awardsapp.Image'),
        ),
    ]
