# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-14 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0017_auto_20181012_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='picture/'),
        ),
    ]
